import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import { Toaster } from "sonner";
import ChatButton from "@/components/global/ChatButton";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // Regular and Bold weights
  style: ['normal', 'italic'], // Normal and Italic styles
  display: 'swap',
  variable: '--font-poppins', // Optional: Define a CSS variable for the font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable}  antialiased bg-white dark:bg-black `} suppressHydrationWarning={true}>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          <Toaster />
          {children}
        </ThemeProvider>
        <ChatButton/>
      </body>
    </html>
  );
}
